name: Build-Release-Publish

on:
  push:
    branches:
      - main
      - release/atcoder
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: ac-library-csharp.slnx

jobs:
  get-version:
    uses: kzrnm/dotnet-actions/.github/workflows/get-version.yml@v2
    with:
      project-path: Directory.Build.props

  format:
    uses: kzrnm/dotnet-actions/.github/workflows/format.yml@v2
    with:
      target: ac-library-csharp.slnx
      dotnet-version: |
        9.0.x
        10.0.x
  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v2
    with:
      target: ac-library-csharp.slnx
      test-logger: GitHubActions
      dotnet-version: |
        9.0.x
        10.0.x

  build-verify:
    needs: get-version
    uses: ./.github/workflows/reusable_verify.yml
    with:
      upload-artifact: ${{ fromJson(needs.get-version.outputs.is-new) }}

  publish:
    runs-on: ubuntu-latest
    needs: [get-version, test, format, build-verify]
    if: ${{ needs.get-version.outputs.is-new == 'true' }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: naminodarie
      - name: Publish NuGet & Release
        uses: kzrnm/dotnet-actions/actions/publish@v2
        id: get-version
        with:
          artifact-name: dist
          version: ${{ needs.get-version.outputs.version }}
          is-prerelease: ${{ needs.get-version.outputs.is-prerelease == 'true' }}
          NUGET_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
