name: Build-Release-Publish-GenericMath

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: AtCoderLibrary.sln

jobs:
  get-version:
    uses: kzrnm/dotnet-actions/.github/workflows/get-version.yml@v1
    with:
      project-path: Directory.Build.props

  build:
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            6.0.x
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ env.WORKFLOW_BUILD_SLN }} -c Release
      - name: Test
        run: dotnet test ${{ env.WORKFLOW_BUILD_SLN }} --no-build --logger GitHubActions -c Release
      - uses: actions/upload-artifact@v1
        if: ${{ needs.get-version.outputs.is-new == 'true' }}
        with:
          name: dist
          path: bin/Packages/Release

  publish:
    needs: [get-version, build, format, library-checker]
    if: ${{ needs.get-version.outputs.is-new == 'true' }}
    uses: kzrnm/dotnet-actions/.github/workflows/publish.yml@v1
    with:
      artifact-name: dist
      version: ${{ needs.get-version.outputs.version }}
      is-prerelease: ${{ needs.get-version.outputs.is-prerelease == 'true' }}
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
