name: test

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: false
        type: boolean
        default: false

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: ac-library-csharp.sln

jobs:
  build-resolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            7.0.x
            9.0.x
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: openssl 1.0
        shell: bash
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
          sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
      - name: Build
        shell: bash
        run: dotnet build $WORKFLOW_BUILD_SLN -c Release
      - name: setup CompetitiveVerifierCsResolver
        shell: bash
        run: dotnet tool install -g CompetitiveVerifierCsResolver
      - name: Unit test
        run: dotnet test $UNITTEST_CSPROJ --logger "CompetitiveVerifier;OutDirectory=${{runner.temp}}/VerifierCsUnitTestResult" --no-build  -c Release
        env:
          UNITTEST_CSPROJ: Test/ac-library-csharp.Test/ac-library-csharp.Test.csproj

      - name: Resolve netcoreapp3.1
        run: dotnet run --project $VERIFY_CSPROJ --framework $FRAMEWORK --no-launch-profile --no-build -c Release | tee "${{runner.temp}}/problems-$FRAMEWORK.json"
        env:
          VERIFY_CSPROJ: Test/ac-library-csharp.LibraryChecker/ac-library-csharp.LibraryChecker.csproj
          FRAMEWORK: netcoreapp3.1
      - name: Resolve net7.0
        run: dotnet run --project $VERIFY_CSPROJ --framework $FRAMEWORK --no-launch-profile --no-build -c Release | tee "${{runner.temp}}/problems-$FRAMEWORK.json"
        env:
          VERIFY_CSPROJ: Test/ac-library-csharp.LibraryChecker/ac-library-csharp.LibraryChecker.csproj
          FRAMEWORK: net7.0
      - name: Resolve net9.0
        run: dotnet run --project $VERIFY_CSPROJ --framework $FRAMEWORK --no-launch-profile --no-build -c Release | tee "${{runner.temp}}/problems-$FRAMEWORK.json"
        env:
          VERIFY_CSPROJ: Test/ac-library-csharp.LibraryChecker/ac-library-csharp.LibraryChecker.csproj
          FRAMEWORK: net9.0

      - name: cs-resolve
        uses: competitive-verifier/actions/cs-resolve@v2
        with:
          solution: ${{ env.WORKFLOW_BUILD_SLN }}
          output-path: verify_files.json
          include: Source/ac-library-csharp/** Test/ac-library-csharp.LibraryChecker/** Test/ac-library-csharp.Test
          exclude: Test/ac-library-csharp.LibraryChecker/BaseSolver.cs **/obj/**
          unittest-result: ${{runner.temp}}/VerifierCsUnitTestResult/*.csv
          problems: ${{runner.temp}}/problems-*.json
          msbuild-properties: Configuration=Release
      - name: Upload verify_files.json
        uses: competitive-verifier/actions/upload-verify-artifact@v2
        with:
          file: verify_files.json
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{github.sha}}
          path: Test/ac-library-csharp.LibraryChecker/bin/Release

      - name: Upload packages
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifact
        with:
          name: dist
          path: bin/Packages/Release

  verify:
    runs-on: ubuntu-latest
    needs: [build-resolve]
    env:
      SPLIT_SIZE: 6
    strategy:
      matrix:
        # prettier-ignore
        index:
          ["0", "1", "2", "3", "4", "5"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          python-version: "3.9"
          cache-pip: true

      - name: Download verify_files.json
        uses: competitive-verifier/actions/download-verify-artifact@v2

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            7.0.x
            9.0.x
      - name: openssl 1.0
        shell: bash
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
          sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binary-${{github.sha}}
          path: Test/ac-library-csharp.LibraryChecker/bin/Release

      - name: Verify
        uses: competitive-verifier/actions/verify@v2
        with:
          destination: ${{runner.temp}}/result.json
          split-size: ${{ env.SPLIT_SIZE }}
          split-index: ${{ matrix.index }}
          write-summary: true
          check: true
